// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1Iu1QyAtPwCkQtNikgbR1ZzONUwM5mrI',
    appId: '1:1098817651136:web:32e29e46d65d74abb20825',
    messagingSenderId: '1098817651136',
    projectId: 'xloop-tours-invoice',
    authDomain: 'xloop-tours-invoice.firebaseapp.com',
    storageBucket: 'xloop-tours-invoice.firebasestorage.app',
    measurementId: 'G-KNZJZERMSL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_htXQmKwKkO4-3SVFEqiOFKQeEvWNAHQ',
    appId: '1:1098817651136:android:073e31ea1caacb84b20825',
    messagingSenderId: '1098817651136',
    projectId: 'xloop-tours-invoice',
    storageBucket: 'xloop-tours-invoice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsqA51b6Wb5sjyT5I89xIwwRLqZW2DhOs',
    appId: '1:1098817651136:ios:b0e146d25891cc5bb20825',
    messagingSenderId: '1098817651136',
    projectId: 'xloop-tours-invoice',
    storageBucket: 'xloop-tours-invoice.firebasestorage.app',
    iosBundleId: 'com.example.xloopInvoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsqA51b6Wb5sjyT5I89xIwwRLqZW2DhOs',
    appId: '1:1098817651136:ios:b0e146d25891cc5bb20825',
    messagingSenderId: '1098817651136',
    projectId: 'xloop-tours-invoice',
    storageBucket: 'xloop-tours-invoice.firebasestorage.app',
    iosBundleId: 'com.example.xloopInvoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1Iu1QyAtPwCkQtNikgbR1ZzONUwM5mrI',
    appId: '1:1098817651136:web:68572e8fe4e50d9db20825',
    messagingSenderId: '1098817651136',
    projectId: 'xloop-tours-invoice',
    authDomain: 'xloop-tours-invoice.firebaseapp.com',
    storageBucket: 'xloop-tours-invoice.firebasestorage.app',
    measurementId: 'G-VRNQ3VCSKD',
  );
}
